apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-app-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/NeRd-StEyN/Kubaws.git'
    targetRevision: HEAD
    path: helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
